DROP DATABASE IF EXISTS burgers_DB;

CREATE DATABASE burgers_DB;


USE burgers_DB;

CREATE TABLE burgers (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(255),
    devoured BOOLEAN,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

SELECT * FROM burgers;